accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
    path('token_generate', views.GenerateToken, name="generate_token"),
]

app/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name="app"

urlpatterns = [
    path('', views.Home, name="home"),
    path('quiz',views.Quiz , name="quiz")
]

quizapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

class Token(models.Model):
    token = models.CharField(max_length=500 , null=False)
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.token

app/models.py
from django.db import models

# Create your models here.


class QuestionModel(models.Model):
    question = models.CharField(max_length=200,null=True)
    op1 = models.CharField(max_length=200,null=True)
    op2 = models.CharField(max_length=200,null=True)
    op3 = models.CharField(max_length=200,null=True)
    op4 = models.CharField(max_length=200,null=True)
    ans = models.CharField(max_length=200,null=True)
    
    def __str__(self):
        return self.question

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.hashers import BasePasswordHasher, make_password, check_password
from .models import Token
import random
# Create your views here.

def GenerateToken(request):
    if request.user.is_authenticated:
        random_word= "t-o-k-e-n"
        random_int = random.randint(0,100)
        random_ = f"{random_word} + {random_int}"
        token = make_password(random_)
        Token.objects.create(token=token)
    return render(request, "accounts/token.html")

app/views.py
import datetime
from django.shortcuts import redirect, render
from .models import QuestionModel
from accounts.models import Token
from datetime import date, time, timedelta, datetime
from django.contrib.auth.hashers import check_password
from django.contrib import messages
import pytz
# Create your views here.


def Home(request):
    if request.method == "POST":
        name= request.POST["name"]
        email= request.POST["email"]
        token = request.POST["token"]

        if name and token and email:
            try:
                token_check = Token.objects.get(token=token)
            except:
                messages.info(request, "Invalid or Expired Token")
                return redirect("app:home")

            if token_check:
                utc=pytz.UTC
                token_date = token_check.date_created
                time_estimate = timedelta(hours=2) + token_date
                now = datetime.now()
                now_= utc.localize(now)
                if now_ >= time_estimate:
                    return redirect("app:home")
                else:
                    return redirect("app:quiz")
            else:
                None
    return render(request, 'app/index.html')



def Quiz(request):
    if request.method == "POST":
        
        questions=QuestionModel.objects.all()
        score=0
        wrong=0
        correct=0
        total=0
        for q in questions:
            total +=1
            if q.ans ==  request.POST.get(q.question):
                score += 1
                correct += 1
            else:
                wrong+=1
        percent = score/(total*40) *100
        context = {
            'score':score,
            'time': request.POST.get('timer'),
            'correct':correct,
            'wrong':wrong,
            'percent':percent,
            'total':total
        }
        return render(request, 'app/quiz.html', context)   
    return render(request, 'app/quiz.html')            

accounts/templates/accounts/token.html
{% extends 'layouts.html' %}
{% load static %}
{% block content %}


       <div class="form-group">
        <a class="btn action_btn thm_btn" href="{% url 'accounts:generate_token' %}" type="submit">
         Sign up
        </a>
       </div>

      </form>
     </div>
    </div>
   </div>


  

{% endblock %}
<!-- Mirrored from srrafi.com/form-demo/formify/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:52 GMT -->

app/templates/app/index-1.html
<!doctype html>
<html lang="en">


<!-- Mirrored from srrafi.com/form-demo/formify/index-1.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:54 GMT -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="assets/vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/responsive.css">

    <title>Formify</title>
</head>

<body>
    <div class="body_wrapper frm-vh-md-100">
        <div class="formify_body" data-bg-color="#E3F0FF">
            <div class="f_content">
                <div class="container-fluid custom_container">
                    <div class="row">
                        <div class="col-lg-6 formify_content_left text-center">
                            <div class="formify_logo_wrapper">
                                <a href="index-2.html"><img src="assets/img/logo.png" alt=""></a>
                                <p>Complete set of digital forms</p>
                            </div>
                            <img class="img-fluid img" src="assets/img/chat-left.png" alt="">
                        </div>
                        <div class="col-lg-6 formify_content_right">
                            <div class="formify_box ml-auto mr-auto">
                                <h4 class="form_title">Sign in to your account</h4>
                                <a href="#" class="btn btn-social btn-google"><img class="icon"
                                        src="assets/img/google.png" alt="">Sign
                                    in with Google</a>
                                <div class="text-center">
                                    <span class="or-text">or</span>
                                </div>
                                <form action="#" class="signup_form">
                                    <div class="form-group">
                                        <label class="input_title" for="inputEmail">Email</label>
                                        <input type="email" class="form-control" id="inputEmail"
                                            placeholder="Email address" required="">
                                    </div>
                                    <div class="form-group">
                                        <label class="input_title" for="inputPassword">Password</label>
                                        <input type="password" class="form-control" id="inputPassword"
                                            placeholder="*******" required="">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn action_btn thm_btn">Sign in</button>
                                    </div>
                                    <p class="form_footer_text">Forgot your password <a href="#">click here to reset</a>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="assets/js/jquery-3.4.1.min.js"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="assets/vendors/bootstrap/js/popper.min.js"></script>
    <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/main.js"></script>

</body>


<!-- Mirrored from srrafi.com/form-demo/formify/index-1.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:54 GMT -->
</html>

app/templates/app/index-2.html
<!doctype html>
<html lang="en">


<!-- Mirrored from srrafi.com/form-demo/formify/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:54 GMT -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="assets/vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="assets/css/style.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/responsive.css">

    <title>Formify</title>
</head>

<body>
    <div class="body_wrapper frm-vh-md-100">
        <div class="formify_body" data-bg-color="#E3F0FF">
            <div class="f_content">
                <div class="container-fluid custom_container">
                    <div class="row">
                        <div class="col-lg-6 formify_content_left text-center">
                            <div class="formify_logo_wrapper">
                                <a href="index-2.html"><img src="assets/img/logo.png" alt=""></a>
                                <p>Complete set of digital forms</p>
                            </div>
                            <img class="img-fluid img" src="assets/img/chat-left.png" alt="">
                        </div>
                        <div class="col-lg-6 formify_content_right">
                            <div class="formify_box ml-auto mr-auto">
                                <h4 class="form_title">Sign up to Formify</h4>
                                <a href="#" class="btn btn-social btn-google"><img class="icon"
                                        src="assets/img/google.png" alt="">Sign
                                    up with Google</a>
                                <div class="text-center">
                                    <span class="or-text">or</span>
                                </div>
                                <form action="#" class="signup_form">
                                    <div class="form-group">
                                        <label class="input_title" for="inputName">Name</label>
                                        <input type="text" class="form-control" id="inputName" placeholder="Enter Your Name" required="">
                                    </div>
                                    <div class="form-group">
                                        <label class="input_title" for="inputEmail">Email</label>
                                        <input type="email" class="form-control" id="inputEmail"
                                            placeholder="Email address" required="">
                                    </div>
                                    <div class="form-group">
                                        <label class="input_title" for="inputPassword">Password</label>
                                        <input type="password" class="form-control" id="inputPassword"
                                            placeholder="*******" required="">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn action_btn thm_btn">Sign up</button>
                                    </div>
                                    <p class="form_footer_text">Already have an account? <a href="index-1.html">Sign in</a>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <script src="assets/js/jquery-3.4.1.min.js"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="assets/vendors/bootstrap/js/popper.min.js"></script>
    <script src="assets/vendors/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/main.js"></script>

</body>


<!-- Mirrored from srrafi.com/form-demo/formify/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:54 GMT -->
</html>

app/templates/app/index.html
{% extends 'layouts.html' %}
{% load static %}
{% block content %}
<div class="formify_body" data-bg-color="#E3F0FF">
 <div class="f_content">
  <div class="container-fluid custom_container">
   <div class="row">
    <div class="col-lg-6 formify_content_left text-center">
     <div class="formify_logo_wrapper">
      <a href="index-2.html">
       <img alt="" src="{% static 'assets/img/logo.png' %}"/>
      </a>
      <p>
       Complete set of digital forms
      </p>
     </div>
     <img alt="" class="img-fluid img" src="{% static 'assets/img/chat-left.png' %}"/>
    </div>
    <div class="col-lg-6 formify_content_right">
     <div class="formify_box ml-auto mr-auto">
      <h4 class="form_title">
       Sign up to Quiz
     
      <div class="text-center">
    
      </div>
      <form action="{% url 'app:home' %}" method="post" class="signup_form">
          {% csrf_token %}

          {% if messages %}

          {% for m in messages %}
           <small>{{m.message}}</small> 
          {% endfor %}
          {% endif %}
       <div class="form-group">
        <label class="input_title" for="inputName">
         Name
        </label>
        <input class="form-control" id="inputName" name="name" placeholder="Enter Your Name" required type="text"/>
       </div>
       <div class="form-group">
        <label class="input_title" for="inputEmail">
         Email
        </label>
        <input class="form-control" id="inputEmail" name="email" placeholder="Email address" required type="email"/>
       </div>
       <div class="form-group">
        <label class="input_title" for="inputPassword">
         Token
        </label>
        <input class="form-control" id="inputPassword" name="token" placeholder="Token" required type="text"/>
       </div>
       <div class="form-group">
        <button class="btn action_btn thm_btn" type="submit">
         Sign up
        </button>
       </div>
       <p class="form_footer_text">
        Already have an account?
        <a href="index-1.html">
         Sign in
        </a>
       </p>
      </form>
     </div>
    </div>
   </div>
  </div>
 </div>
</div>

{% endblock %}
<!-- Mirrored from srrafi.com/form-demo/formify/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:52 GMT -->

app/templates/app/quiz.html
{% extends 'layouts.html' %}

{% load static %}

{% block content %}

  <div class="body_wrapper frm-vh-md-100">
   <div class="formify_body formify_signup_fullwidth formify_signup_fullwidth_two d-flex">
    <div class="formify_left_fullwidth formify_left_top_logo frm-vh-md-100 d-flex align-items-center justify-content-center" data-bg-color="#FFEFF9">
     <a class="top_logo" href="index.html">
      <img alt="" src="{% static 'assets/img/logo.png' %}"/>
     </a>
     <img alt="" class="img-fluid" src="{% static 'assets/img/personal_img.png' %}"/>
    </div>
    <div class="formify_right_fullwidth d-flex align-items-center justify-content-center">
     <div class="formify_box formify_box_checkbox background-white">
      <div class="formify_header">
       <h4 class="form_title">
        Ingenious Quiz App
       </h4>
       <p>
        Tell us a little bit about your problems, and we'll show
        <br/>
        you how our SaaS solution
                            can solve them.
       </p>
       <div class="border ml-0">
       </div>
      </div>
      <div class="tab-content" id="myTabContent">
       <div aria-labelledby="One-tab" class="tab-pane fade show active" id="One" role="tabpanel">
        <div class="number">
         1/3
        </div>
        <h6>
         How did you hear about this website?
        </h6>
        <form action="#" class="signup_form">
         <div class="box_info">
          <div class="form-check">
           <input checked="" class="form-check-input" id="budgetOne" name="gridRadios" type="checkbox" value="option1"/>
           <label class="form-check-label" for="budgetOne">
            Social Media
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetTwo" name="gridRadios" type="checkbox" value="option2"/>
           <label class="form-check-label" for="budgetTwo">
            Advertising
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetThree" name="gridRadios" type="checkbox" value="option3"/>
           <label class="form-check-label" for="budgetThree">
            Search Engine
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetFour" name="gridRadios" type="checkbox" value="option4"/>
           <label class="form-check-label" for="budgetFour">
            Friend
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetFive" name="gridRadios" type="checkbox" value="option5"/>
           <label class="form-check-label" for="budgetFive">
            Other
           </label>
          </div>
         </div>
        </form>
        <button class="btn thm_btn next_tab text-transform-inherit">
         Next
        </button>
       </div>
       <div aria-labelledby="Two-tab" class="tab-pane fade" id="Two" role="tabpanel">
        <div class="number">
         2/3
        </div>
        <h6>
         Which device did you use to access the website?
        </h6>
        <form action="#" class="signup_form">
         <div class="box_info">
          <div class="form-check">
           <input class="form-check-input" id="budgetSix" name="gridRadios" type="checkbox" value="option1"/>
           <label class="form-check-label" for="budgetSix">
            Desktop
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetSeven" name="gridRadios" type="checkbox" value="option2"/>
           <label class="form-check-label" for="budgetSeven">
            Laptop
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetEight" name="gridRadios" type="checkbox" value="option3"/>
           <label class="form-check-label" for="budgetEight">
            Pad
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetNine" name="gridRadios" type="checkbox" value="option4"/>
           <label class="form-check-label" for="budgetNine">
            Mobile
           </label>
          </div>
         </div>
        </form>
        <button class="btn thm_btn next_tab text-transform-inherit">
         Next
        </button>
       </div>
       <div aria-labelledby="Three-tab" class="tab-pane fade" id="Three" role="tabpanel">
        <div class="number">
         3/3
        </div>
        <h6>
         Are you satisfied that you found out the website?
        </h6>
        <form action="#" class="signup_form">
         <div class="box_info">
          <div class="form-check">
           <input class="form-check-input" id="budgetTen" name="gridRadios" type="checkbox" value="option1"/>
           <label class="form-check-label" for="budgetTen">
            Very Satisfied
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetEleven" name="gridRadios" type="checkbox" value="option2"/>
           <label class="form-check-label" for="budgetEleven">
            Satisfied
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetTweleve" name="gridRadios" type="checkbox" value="option3"/>
           <label class="form-check-label" for="budgetTweleve">
            Neutral
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetThirteen" name="gridRadios" type="checkbox" value="option4"/>
           <label class="form-check-label" for="budgetThirteen">
            Unsatisfied
           </label>
          </div>
          <div class="form-check">
           <input class="form-check-input" id="budgetFourteen" name="gridRadios" type="checkbox" value="option5"/>
           <label class="form-check-label" for="budgetFourteen">
            Very unsatisfied
           </label>
          </div>
         </div>
         <button class="btn thm_btn text-transform-inherit" type="submit">
          Submit
         </button>
        </form>
       </div>
      </div>
      <ul class="nav nav-tabs form_tab" id="myTab" role="tablist">
       <li class="nav-item">
        <a aria-controls="One" aria-selected="true" class="nav-link active" data-toggle="tab" href="#One" id="One-tab" role="tab">
        </a>
       </li>
       <li class="nav-item">
        <a aria-controls="Two" aria-selected="false" class="nav-link" data-toggle="tab" href="#Two" id="Two-tab" role="tab">
        </a>
       </li>
       <li class="nav-item">
        <a aria-controls="Three" aria-selected="false" class="nav-link" data-toggle="tab" href="#Three" id="Three-tab" role="tab">
        </a>
       </li>
      </ul>
     </div>
    </div>
   </div>
  </div>
  

  {% endblock %}

templates/layouts.html
<!DOCTYPE html>
<html lang="en">
 <!-- Mirrored from srrafi.com/form-demo/formify/ by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 16 Nov 2021 12:59:44 GMT -->
 <head>
    {% load static %}
  <!-- Required meta tags -->
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <!-- Bootstrap CSS -->
  <link href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
  <link href="{% static 'assets/css/responsive.css' %}" rel="stylesheet"/>
  <title>
    Quiz App
  </title>
 </head>
 <body>
  {% block content %}

    {% endblock %}
  <!-- Optional JavaScript; choose one of the two! -->
  <script src="{% static 'assets/js/jquery-3.4.1.min.js' %}">
  </script>
  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="{% static 'assets/vendors/bootstrap/js/popper.min.js' %}">
  </script>
  <script src="{% static 'assets/vendors/bootstrap/js/bootstrap.min.js' %}">
  </script>
  <script src="{% static 'assets/js/main.js' %}">
  </script>
 </body>
</html>